dependencies:
  - python=3.8
  - numpy==1.22.4
  - pytest==6.2.5
  - jupyterlab==3.4.4
  - ipywidgets==7.7.1
  - jupyter-dash==0.4.2
  - matplotlib==3.5.2
  - plotly==5.9.0
  - pandas==1.4.3
  - scipy==1.9.1