name: life123-environment
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.26.4
  - pytest=6.2.5
  - jupyterlab=3.6.8
  - ipywidgets=7.7.1
  - jupyter-dash=0.4.2
  - plotly=5.24.1
  - pandas=1.5.3
  - scipy=1.13.1
  - pip
  - pip:
      - ipynbname==2024.1.0.0